import { Controller, Get } from '@nestjs/common';
import { Snapshot, SnapshotsService } from './snapshots.service';

@Controller('snapshots')
export class SnapshotsController {
  constructor(private snapshotsService: SnapshotsService) {}

  // Read side: lists the snapshots generated by the event listener.
  // Empty until a POST /accounts fires the event (state is in-memory).
  @Get()
  getSnapshots(): Snapshot[] {
    return this.snapshotsService.getSnapshots();
  }
}
